server:
  port: 80




spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 106.12.15.56:8848


feign:
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
        circuitBreaker:
          requestVolumeThreshold: 4

