server:
  port: 9527



spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 106.12.15.56:8848
    gateway:
      routes:
        - id: order-gateway
          uri: lb://order-service
          predicates:
            - Path=/order/**