server:
  port: 9527



spring:
  application:
    name: gateway-service
  cloud:
    zookeeper:
      connect-string: 106.12.15.56:2181
    gateway:
      routes:
        - id: order-gateway
          uri: lb://order-service
          predicates:
            - Path=/order/**