server:
  port: 9527



spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://106.12.15.56:9411
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: 106.12.15.56:8848
    gateway:
      routes:
        - id: order-gateway
          uri: lb://order-service
          predicates:
            - Path=/order/**