server:
  port: 8002

spring:
  application:
    name: payment-service
  zipkin:
    base-url: http://106.12.15.56:9411
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: 106.12.15.56:8848
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 106.12.15.56
                port: 5672
                username: admin
                password: admin
                virtual-host: /
      defaultBinder: defaultRabbit
      default:
        content-type: application/json
        binder: defaultRabbit
      bindings:
        orderInput:
          destination: order
          group: payment-service